// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpAM4N0ErN3pbRdSBiYTWQur7zIgWJE3Y',
    appId: '1:1091369773101:web:b5ad0278b022351c9ff0a4',
    messagingSenderId: '1091369773101',
    projectId: 'todofirebase-70837',
    authDomain: 'todofirebase-70837.firebaseapp.com',
    storageBucket: 'todofirebase-70837.firebasestorage.app',
    measurementId: 'G-TDMMPJME9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPB0JwiptL-tLcfDqjST8PFmznY5n_SM',
    appId: '1:1091369773101:android:eb3ba30243dd50569ff0a4',
    messagingSenderId: '1091369773101',
    projectId: 'todofirebase-70837',
    storageBucket: 'todofirebase-70837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-zQ6mMtqsa3IxHXUQM70E-mwmoeAIJQ',
    appId: '1:1091369773101:ios:8df7872d3d765aa59ff0a4',
    messagingSenderId: '1091369773101',
    projectId: 'todofirebase-70837',
    storageBucket: 'todofirebase-70837.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-zQ6mMtqsa3IxHXUQM70E-mwmoeAIJQ',
    appId: '1:1091369773101:ios:8df7872d3d765aa59ff0a4',
    messagingSenderId: '1091369773101',
    projectId: 'todofirebase-70837',
    storageBucket: 'todofirebase-70837.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpAM4N0ErN3pbRdSBiYTWQur7zIgWJE3Y',
    appId: '1:1091369773101:web:e632a9d23932ead39ff0a4',
    messagingSenderId: '1091369773101',
    projectId: 'todofirebase-70837',
    authDomain: 'todofirebase-70837.firebaseapp.com',
    storageBucket: 'todofirebase-70837.firebasestorage.app',
    measurementId: 'G-GGHBC2921F',
  );

}